server:
  port: 8072

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: product-service
          uri: lb://product-service   # Use load-balanced URI for dynamic discovery
          predicates:
            - Path=/products/**
          filters:
            - StripPrefix=1
    consul:
      host: consul
      port: 8500
      discovery:
        healthCheckInterval: 5s
        preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
